version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: vms_db
    environment:
      MYSQL_DATABASE: vms
      MYSQL_USER: tmnhat
      MYSQL_PASSWORD: 123123123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: